server:
  port: 9092
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: PostDB
      username: bilge
      password: bilge!123
userprofileservice:
  secret:
    secret-key: ${JAVA14_SECRET_KEY}
    issuer: ${JAVA14_ISSUER}