server:
  port: 8888

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/hcaslan/java14ConfigServerSocialMedia.git"
          default-label: "main"
          skip-ssl-validation: true
          username: ${GIT_NAME}
          password: ${GIT_TOKEN_JAVA14}
